MONGODB_HOST: mongodb-{{env}}.vinaydevops.online
REDIS_HOST: redis-{{env}}.vinaydevops.online
MYSQL_HOST: mysql-{{env}}.vinaydevops.online
RABBITMQ_HOST: rabbitmq-{{env}}.vinaydevops.online
CATALOGUE_HOST: catalogue.backend-alb-{{env}}.vinaydevops.online
USER_HOST: user.backend-alb-{{env}}.vinaydevops.online
CART_HOST: cart.backend-alb-{{env}}.vinaydevops.online
SHIPPING_HOST: shipping.backend-alb-{{env}}.vinaydevops.online
PAYMENT_HOST: payment.backend-alb-{{env}}.vinaydevops.online